# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearbyCafe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearbyCafe
  pod 'GoogleMaps', '7.0.0'
  pod 'GooglePlaces', '7.0.0'

end
